name: release-tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.11'
      - run: |
          make update-flagd
          go mod tidy
          make controller-gen
          IMG=ghcr.io/open-feature/open-feature-operator:${GITHUB_REF#refs/*/} make release-manifests

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            config/webhook/certificate.yaml
            config/rendered/release.yaml
            config/samples/end-to-end.yaml
